= Data Product

In the context of the _Visie Datadelen_, the approach to data exchange has been
explicitly framed in terms of _data products_. A data product integrates the
semantic, technical, and usage aspects of data exchange. To facilitate this, a
data product is composed of the following components:

* _Dataset_: The actual data being exchanged. Think of a dataset as a table of
data, where the columns describe the type of data provided for each row. For
example, a dataset for connections will include, at a minimum, a column
labelled "Connection Number," with each row describing a unique connection.
* _Dataservice_: The technical method by which the dataset is distributed. This
concerns how the data is made accessible, whether as a file, through an API,
via a database, or on a file server.
* _Conditions_: There may be conditions applied to aspects such as
availability, quality, classification, and purpose limitation concerning the
use of the data product.

The data product combines the dataset and dataservice, enhanced with conditions
for usage.
